version: '3.9'

services:
  backend:
    container_name: python-backend
    build: .
    restart: always
    ports:
      - "8068:8068"
    environment:
      DB_HOST: mysql       
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: veha
      DB_PASSWORD: vehacgg123
    depends_on:
      - mysql
    volumes:
      - ./:/app
      - /app/__pycache__

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: panel-password
      MYSQL_DATABASE: mydb
      MYSQL_USER: veha
      MYSQL_PASSWORD: vehacgg123
    ports:
      - "33063:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
